## https://taskfile.dev/usage/
version: 3

silent: true

output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Install and configure Samba
    summary: |
      Installs Samba and Avahi, enables and starts Avahi, and configures Samba.
      If local M$ Windows mounts file is present, it creates samba configs for them as well.
    cmds:
      - |
        type fd &> /dev/null || {{.PARU}} fd
        type yq &> /dev/null || {{.PARU}} go-yq
        type hostname &> /dev/null || {{.PARU}} inetutils
        type samba &> /dev/null || {{.PARU}} samba
        type avahi-daemon &> /dev/null || {{.PARU}} avahi
      - |
        set -x
        sudo systemctl is-enabled avahi-daemon &>/dev/null || \
          sudo systemctl enable avahi-daemon
        sudo systemctl is-active avahi-daemon &>/dev/null || \
          sudo systemctl start avahi-daemon
        sudo {{.CP}} etc/samba /etc/
      - |
        SMB_DEFAULT_GROUP=${SMB_DEFAULT_GROUP:-smb}
        ## Create the group if it doesn't exist
        sudo getent group "$SMB_DEFAULT_GROUP" &>/dev/null || \
          { set -x; sudo groupadd "$SMB_DEFAULT_GROUP"; { set +x; } 2>/dev/null; }
        ## Add current user to the samba group
        [[ " $(id -Gn) " =~ $SMB_DEFAULT_GROUP ]] || \
          { set -x; sudo usermod -aG $SMB_DEFAULT_GROUP $USER; { set +x; } 2>/dev/null; }
        ## Add current user to samba
        sudo pdbedit -L | grep -qP "^$USER:" || \
          { set -x; sudo smbpasswd -a "$USER"; { set +x; } 2>/dev/null; }
        ## Create samba configs for existing mounts
        SMB_CONF_DIR="/etc/samba/smb.conf.d"
        sudo test -d "$SMB_CONF_DIR" || \
          { set -x; sudo mkdir -p "$SMB_CONF_DIR"; { set +x; } 2>/dev/null; }
        MOUNTS=$(cat ../03-mounts/mounts.$(hostname).yaml) || exit 0
        for NAME in $(yq 'keys[]' <<< "$MOUNTS"); do
          DEST=$(yq -r ".${NAME}.destination" - <<< "$MOUNTS")
          FILE="$SMB_CONF_DIR/${NAME}.conf"
          ## Backup existing
          sudo ../../scripts/backup.sh "$FILE"
          ## Write new
          cat <<! | sudo tee "$FILE" >/dev/null
        [$NAME]
        comment = $NAME
        path = $DEST
        valid users = @$SMB_DEFAULT_GROUP
        public = no
        writable = yes
        !
          ## Include the config in the main smb.conf
          sudo grep -qP "^include\s*=\s*$FILE" "/etc/samba/smb.conf" || \
            { set -x; sudo tee -a "/etc/samba/smb.conf" <<< "include = $FILE" >/dev/null; { set +x; } 2>/dev/null; }
        done
        ## Enable and restart samba service
        set -x
        sudo systemctl is-enabled smb &>/dev/null || \
          sudo systemctl enable smb
        sudo systemctl is-active smb &>/dev/null || \
          sudo systemctl restart smb
