## https://taskfile.dev/usage/
version: 3

silent: true

output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Cleanup the system
    cmds:
      - |
        PACKAGES=$(yq --no-colors --no-doc '.*[] | select(.state=="absent").name' $(fd packages.yaml ../ | tr '\n' ' ') || true)
        for PKG in $PACKAGES; do
          paru -Q $PKG &>/dev/null || continue
          set -x
          {{.PARU_REMOVE}} $PKG || { set +x; } 2>/dev/null
          { set +x; } 2>/dev/null
        done
      - |
        for F in fish kate; do
          for P in ~/.config/$F ~/.local/share/$F; do
            [[ -e "$P" ]] || continue
            set -x
            rm --verbose --force --recursive $P
            { set +x; } 2>/dev/null
          done
        done
