## https://taskfile.dev/usage/
version: 3

silent: true

output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Install looking-glass
    cmds:
      - |
        type looking-glass-client &>/dev/null || {{.PARU}} looking-glass-rc
        paru -Q looking-glass-rc-module-dkms &>/dev/null || {{.PARU}} looking-glass-rc-module-dkms
      - task: inst:copy
        vars:
          DIR: copy
      - |
        echo ">> Downgrade EFI OVMF firmware that works with Looking Glass kvmfr module"
        VERSION=202208-3
        set -x
        paru -Q edk2-ovmf=${VERSION} &>/dev/null || \
          paru -U --noconfirm --needed https://archive.archlinux.org/packages/e/edk2-ovmf/edk2-ovmf-${VERSION}-any.pkg.tar.zst
        sudo sed -i -E 's,^#?\s*(IgnorePkg\s*=\s*).*,\1 edk2-ovmf,' /etc/pacman.conf
