## https://taskfile.dev/usage/
version: 3

silent: true

# output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Install KDE Plasma packages
    deps:
      - inst:initool
    cmds:
      - task: inst:packages
      - task: inst:symlink_files
      - vars:
          SUDO: sudo
          FILE: /etc/environment
          KEY: GTK_USE_PORTAL
          VALUE: 1
        task: inst:iniset
