[manager]
show_hidden = true
ratio = [1, 2, 4]
linemode = "size"

[preview]
max_width = 3000
max_height = 4000
image_delay = 100
wrap = "yes"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
