## https://taskfile.dev/usage/
version: 3

silent: true

output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Network configuration tasks
    cmds:
      - |
        type sshd &>/dev/null || {{.PARU}} openssh
        sudo systemctl enable sshd
        sudo systemctl restart sshd
      - task: firewall

  firewall:
    desc: Configure system firewall
    cmds:
      - type ufw &>/dev/null || {{.PARU}} ufw
      - sudo ufw disable
