[settings]
experimental = true # enable experimental features
env_file = '.env'

[tools]
"go:github.com/1pkg/gopium" = "latest"
"pulumi" = "3"
"ubi:sigstore/cosign" = { version = "2", exe = "cosign-linux-amd64", rename_exe = "cosign" }
