## https://taskfile.dev/usage/
version: 3

silent: true

output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Install video drivers and utilities
    cmds:
      - task: inst:symlink
        vars:
          DIR: symlink
      - |
        type lspci || {{.PARU}} pciutils
      - |
        ## Crude detection
        PREV=
        for VGA in $(lspci | grep VGA | awk '{print $5}'); do
          [[ "$VGA" == "$PREV" ]] && continue
          PREV=$VGA
          echo "$VGA VGA detected"
          case $VGA in
            NVIDIA)
              ADDITIONAL=aur/nvidia-patch
              V1=$(paru -Si $ADDITIONAL | grep ^Version | cut -d: -f2 | head -1)
              V2=$(paru -Si nvidia-utils | grep ^Version | cut -d: -f2 | head -1)
              [[ "$V1" == "$V2" ]] || ADDITIONAL=
              set -x
              {{.PARU}} $ADDITIONAL opencl-nvidia lib32-nvidia-utils lib32-opencl-nvidia libva-nvidia-driver cuda nvidia-container-toolkit
              { set +x; } 2>/dev/null
              ;;
            Advanced)
              set -x
              {{.PARU}} mesa lib32-mesa opencl-mesa lib32-opencl-mesa vulkan-radeon lib32-vulkan-radeon xf86-video-amdgpu amdgpu_top radeontop
              { set +x; } 2>/dev/null
              ;;
            ## TODO Test
            Intel)
              set -x
              {{.PARU}} mesa lib32-mesa vulkan-intel lib32-vulkan-intel
              { set +x; } 2>/dev/null
              ;;
          esac
        done
