## https://taskfile.dev/usage/
version: 3

silent: true

output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Install generic desktop packages
    cmds:
      - task: inst:packages
      - task: inst:symlink
        vars:
          DIR: symlink
      - task: gaming_config
      - task: rustdesk_configure
      - task: catppuccin_gtk_theme

  gaming_config:
    desc: Configure Sunshine
    cmds:
      - |
        type gamescope &>/dev/null || exit 0
        BIN=$(readlink -e $(which gamescope))
        set -x
        sudo setcap 'cap_sys_nice=eip' "$BIN"
      - |
        type sunshine &>/dev/null || exit 0
        BIN=$(readlink -e $(which sunshine))
        set -x
        sudo setcap cap_sys_admin+p "$BIN"

  rustdesk_configure:
    desc: Configure RustDesk
    vars:
      SERVICE: rustdesk
    status:
      - type rustdesk &>/dev/null && exit 1 || exit 0
    cmds:
      - |
        ## Disable system service
        ! sudo systemctl is-enabled {{.SERVICE}} &>/dev/null || \
          sudo systemctl disable {{.SERVICE}}
        ! sudo systemctl is-active {{.SERVICE}} &>/dev/null || \
          sudo systemctl stop {{.SERVICE}}

  catppuccin_gtk_theme:
    desc: Install Catppuccino GTK theme
    cmds:
      - |
        WORKDIR=$HOME/dev
        [[ -d "$WORKDIR" ]] || mkdir -p $WORKDIR
        cd $WORKDIR
        [[ -d "$WORKDIR/Catppuccin-GTK-Theme" ]] || \
          { set -x; git clone https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme.git; { set +x; } 2>/dev/null; }
        cd Catppuccin-GTK-Theme
        set -x
        git pull
        { set +x; } 2>/dev/null
        cd themes
        set -x
        ./install.sh --theme purple --color dark --tweaks black --libadwaita
        { set +x; } 2>/dev/null
        GTK_DIR="$HOME/.config/gtk-3.0"
        [[ -d "$GTK_DIR" ]] || \
          mkdir -p "$GTK_DIR"
        for F in gtk.css gtk-dark.css assets; do
          SRC="$HOME/.themes/Catppuccin-Purple-Dark/gtk-3.0/$F"
          DST="$GTK_DIR/$F"
          test -L "$DST" -a -e "$DST"  || \
            ln --verbose --symbolic --force "$SRC" "$GTK_DIR/" || \
              { RET=$?; delta "$SRC" "$DST"; exit $RET; }
        done
