## https://taskfile.dev/usage/
version: 3

silent: true

output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Install generic desktop packages
    cmds:
      - task: inst:packages
      - task: inst:copy
        vars:
          DIR: copy
      - task: inst:symlink
        vars:
          DIR: symlink
      - sudo {{.CP}} 'symlink/~/.gtkrc-2.0' /root/
      - task: gaming_config
      - task: rustdesk_configure
      - task: catppuccin_gtk_theme

  gaming_config:
    desc: Configure Sunshine
    cmds:
      - |
        type gamescope &>/dev/null || exit 0
        BIN=$(readlink -e $(which gamescope))
        set -x
        sudo setcap 'cap_sys_nice=eip' "$BIN"
      - |
        type sunshine &>/dev/null || exit 0
        BIN=$(readlink -e $(which sunshine))
        set -x
        sudo setcap cap_sys_admin+p "$BIN"

  rustdesk_configure:
    desc: Configure RustDesk
    vars:
      SERVICE: rustdesk
    status:
      - type rustdesk &>/dev/null && exit 1 || exit 0
    cmds:
      - |
        ## Disable system service
        ! sudo systemctl is-enabled {{.SERVICE}} &>/dev/null || \
          sudo systemctl disable {{.SERVICE}}
        ! sudo systemctl is-active {{.SERVICE}} &>/dev/null || \
          sudo systemctl stop {{.SERVICE}}

  catppuccin_gtk_theme:
    desc: Setup Catppuccino GTK theme
    cmds:
      - |
        paru -Q catppuccin-gtk-theme-mocha-revamped &>/dev/null || \
          paru -Sy --noconfirm aur/catppuccin-gtk-theme-mocha-revamped
      - |
        THEME=lavender
        for D in gtk-3.0 gtk-4.0; do
          GTK_DIR="$HOME/.config/$D"
          [[ -d "$GTK_DIR" ]] || \
            mkdir -p "$GTK_DIR"
          for F in thumbnail.png gtk.css gtk-dark.css assets; do
            SRC="/usr/share/themes/catppuccin-mocha-$THEME-standard+default/$D/$F"
            DST="$GTK_DIR/$F"
            test -L "$DST" -a -e "$DST"  || \
              ln --verbose --symbolic --force "$SRC" "$GTK_DIR/" || \
                { RET=$?; delta "$SRC" "$DST"; exit $RET; }
          done
        done
