## https://taskfile.dev/usage/
version: 3

silent: true

# output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Install generic desktop packages
    cmds:
      - task: inst:packages
      - task: inst:symlink
        vars:
          DIR: symlink
      - task: gaming_config
      - task: rustdesk_configure
      - vars:
          SUDO: sudo
          FILE: /etc/environment
          KEY: XCURSOR_THEME
          VALUE: Bibata-Modern-Amber
        task: inst:iniset

  gaming_config:
    desc: Configure Sunshine
    cmds:
      - |
        type gamescope &>/dev/null || exit 0
        BIN=$(readlink -e $(which gamescope))
        set -x
        sudo setcap 'cap_sys_nice=eip' "$BIN"
      - |
        type sunshine &>/dev/null || exit 0
        BIN=$(readlink -e $(which sunshine))
        set -x
        sudo setcap cap_sys_admin+p "$BIN"

  rustdesk_configure:
    desc: Configure RustDesk
    vars:
      SERVICE: rustdesk
    status:
      - type rustdesk &>/dev/null && exit 1 || exit 0
    cmds:
      - |
        ## Disable system service
        ! sudo systemctl is-enabled {{.SERVICE}} &>/dev/null || \
          sudo systemctl disable {{.SERVICE}}
        ! sudo systemctl is-active {{.SERVICE}} &>/dev/null || \
          sudo systemctl stop {{.SERVICE}}
