--disable-gpu-vsync
--disable-frame-rate-limit
--enable-zero-copy
--enable-cast-streaming-with-hidpi
--flag-switches-begin
--cast-streaming-force-enable-hardware-h264
--cast-streaming-force-enable-hardware-vp8
--cast-streaming-force-enable-hardware-vp9
--enable-features=VaapiVideoDecoder,AcceleratedVideozDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,CastStreamingAv1,CastStreamingHardwareHevc,CastStreamingMediaVideoEncoder
--disable-features=AutoPictureInPictureForVideoPlayback
--flag-switches-end
