--ozone-platform=wayland
--disable-gpu-vsync
--disable-frame-rate-limit
--ignore-gpu-blocklist
--enable-unsafe-webgpu
--enable-gpu-rasterization
--enable-zero-copy
--enable-cast-streaming-with-hidpi
--cast-streaming-force-enable-hardware-h264
--cast-streaming-force-enable-hardware-vp8
--cast-streaming-force-enable-hardware-vp9
--enable-features=VaapiOnNvidiaGPUs,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,CastStreamingAv1,CastStreamingHardwareHevc,CastStreamingMediaVideoEncoder
--disable-features=AutoPictureInPictureForVideoPlayback
