## https://taskfile.dev/usage/
version: 3

silent: true

output: prefixed

set:
  - nounset
  - errexit
  - pipefail

includes:
  inst:
    internal: true
    taskfile: ../../lib/installers.yaml

tasks:
  default:
    desc: Install KDE Plasma packages
    deps:
      - inst:initool
    cmds:
      - task: inst:packages
      - task: inst:copy
        vars:
          DIR: copy
      - task: inst:symlink
        vars:
          DIR: symlink
      - vars:
          SUDO: sudo
          FILE: /etc/environment
          KEY: GTK_USE_PORTAL
          VALUE: 1
        task: inst:iniset
      - |
        ## https://wiki.cachyos.org/configuration/dual_gpu/#kde-plasma
        SERVICE=switcheroo-control
        sudo systemctl is-enabled $SERVICE &>/dev/null || \
          sudo systemctl enable --now $SERVICE
        sudo systemctl is-active $SERVICE &>/dev/null || \
          sudo systemctl start $SERVICE
      - |
        for L in .config/gtk-3.0 .config/gtk-4.0 .config/Trolltech.conf; do
          sudo test -L /root/$L || \
            sudo ln -s $HOME/$L /root/$L
        done
