#!/usr/bin/env bash
# This is a wrapper script to be use by gtk-launch and other gtk stuff
# that is expecting users to ALWAYS use the "gnome-terminal" command.
# -- The HyDE Project --

scrDir="$(dirname "$(realpath "$0")")"
# shellcheck disable=SC1091
source "${scrDir}/globalcontrol.sh"

term=${TERMINAL}
term=${term:-$(gsettings get org.gnome.desktop.default-applications.terminal exec)}
term=${term:-kitty}

$term "$@"
cat <<NOTICE
Note: This is a wrapper script to be use by gtk-launch 
        and other gtk stuff that is expecting users to 
        ALWAYS use the \"gnome-terminal\" command."

-- The HyDE Project --

NOTICE
