## enable or disable automatic update checks
update_check = false

## Set the maximum number of lines Atuin’s interface should take up.
inline_height = 10

## Configure whether or not to show tabs for search and inspect.
show_tabs = false

## Configure whether or not to show the help row, which includes the current Atuin version (and whether an update is available), a keymap hint, and the total amount of commands in your history.
show_help = false

## Invert the UI - put the search bar at the top
invert = true

## Which style to use. Possible values: auto, full and compact.
style = "compact"
