- name: aur/bookokrat-bin
  desc: Terminal-based EPUB and PDF reader with rich TUI
- name: betterbird-bin
  desc: Betterbird is a fine-tuned version of Mozilla Thunderbird, Thunderbird on steroids, if you will.
- name: calibre
  desc: Ebook management application
- name: aur/onlyoffice-bin
  desc: An office suite that combines text, spreadsheet and presentation editors
- name: okular
  desc: Document Viewer
- name: jrnl
  desc: Collect your thoughts and notes without leaving the command line
## To be removed
- name: kate
  desc: Advanced Text Editor
  state: absent
