- name: keepassxc
  desc: Cross-platform community-driven port of Keepass password manager
# - name: aur/git-credential-keepassxc
#   desc: git-credential-keepassxc is a Git credential helper that allows Git (and shell scripts) to get/store logins from/to KeePassXC
- name: x11-ssh-askpass
  desc: Lightweight passphrase dialog for SSH
- name: gcr
  desc: A library for bits of crypto UI and parsing
- name: pinentry
  desc: Collection of simple PIN or passphrase entry dialogs which utilize the Assuan protocol
- name: kleopatra
  desc: Certificate Manager and Unified Crypto GUI
- name: ksshaskpass
  desc: ssh-add helper that uses kwallet and kpassworddialog

## Remove
- name: kwalletmanager
  desc: Wallet management tool
  state: absent
